### PR TITLE
Bug 4410 fixed

### PR DESCRIPTION
**Pull request by AkshayMankar30**
### Proposed changes

*
*

### Related issues

*
*

### Checklist

- [x] I consider the submitted work as finished
- [x] I tested the code for its functionality
- [ ] I wrote test cases for the relevant uses case
- [ ] I added/update the relevant documentation (either on github or on notion)
- [ ] Where necessary I refactored code to improve the overall quality

### Further comments

If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Review by ddavisDarkLight — APPROVED** [review]

**Review by r-joyce — CHANGES_REQUESTED** [review]
The software portion is correct in both how the objects are displayed and when in edit mode.

The other types (Devices and Networks), when in edit mode the current value for asset type is not set. Then the drop down list for asset types for Network objects should have a single entry in the list of 'Network.'

**Review by CyberDaedalus00 — CHANGES_REQUESTED** [review]
For some reason, when you enter Edit for Devices, the value that was shown for the asset_type in the view mode is no longer shown.  The list of assets to choose from is correct.

**Comment by AkshayMankar30** [comment]
I think this is happening because I'm getting  **comput_device** asset_type key from **computingDeviceAsset** API as :

screenshot-studio apollographql com-2021 12 22-20_34_39

 and the **Device Introspection query** returns the following asset_type keys

screenshot-studio apollographql com-2021 12 22-20_33_14

and I can't see the **comput_device** asset_type in **Device Introspection query** 
 so I think that's why the Asset Type field does not show the Asset Type field on the **Device Edit** view page

**Review by CyberDaedalus00 — CHANGES_REQUESTED** [review]
For some reason there is a conflict when I tried to merge this branch with the latest develop branch
.  
CONFLICT (content): Merge conflict in opencti-platform/opencti-front/src/private/components/common/stix_domain_objects/CyioDomainObjectAssetCreationOverview.js

There are far too many differences for a non-UI person like me to determine the correct solution, so I need this addressed before we can merge it in

**Pull request merged**
