### PR TITLE
AB#5718

### PR DESCRIPTION
**Pull request by sachin755**
### Proposed changes

*
*

### Related issues

*
*

### Checklist

- [x] I consider the submitted work as finished
- [x] I tested the code for its functionality
- [ ] I wrote test cases for the relevant uses case
- [ ] I added/update the relevant documentation (either on github or on notion)
- [ ] Where necessary I refactored code to improve the overall quality

### Further comments

If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by johnjdl** [comment]
@r-joyce, I checked the local build and it looks good could you review and merge? It looks like w have a failed test for the continuous-integration for the PR though.

**Comment by r-joyce** [comment]
I ran this locally and it rendered a little weird for me. It looks like the feature was added and it looks to be able to collapse correctly, but the spacing of the links (and the horizontal break bar) seem to have lost their styling with how the code is broken out now. Is this how we want it @johnjdl?
image

**Comment by johnjdl** [comment]
> I ran this locally and it rendered a little weird for me. It looks like the feature was added and it looks to be able to collapse correctly, but the spacing of the links (and the horizontal break bar) seem to have lost their styling with how the code is broken out now. Is this how we want it @johnjdl? image

Ok, trying to run this locally again, I didn't run into this weird spacing.

**Comment by johnjdl** [comment]
@r-joyce I think we're good to merge this, the updates from secutree look have to improved the positioning of the bottom links.

**Review by r-joyce — APPROVED** [review]
Nice, looks good to me!

**Pull request merged**
