### PR TITLE
- Added pending progress bar to Scan page

### PR DESCRIPTION
**Pull request by ddavisDarkLight**
- Close Upload Modal when Scan is done uploading
- Supressed ES Lint warnings

### Proposed changes

*
*

### Related issues

*
*

### Checklist

- [ ] I consider the submitted work as finished
- [ ] I tested the code for its functionality
- [ ] I wrote test cases for the relevant uses case
- [ ] I added/update the relevant documentation (either on github or on notion)
- [ ] Where necessary I refactored code to improve the overall quality

### Further comments

If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Review by CyberDaedalus00 — COMMENTED** [review]
these seem straightforward to me.

**Review by r-joyce — APPROVED** [review]
Looks good to me

**Review by DallasP9124 — APPROVED** [review]
Looks fine. But was it necessary to to add ignore eslint to all those files?

**Comment by ddavisDarkLight** [comment]
I was hoping the front end build time would increase. Also the false that contain /* refactor */ are files that Secutree need to take a look at

**Comment by DallasP9124** [comment]
@r-joyce care to deploy

**Pull request merged**
