### PR TITLE
AB#4934

### PR DESCRIPTION
**Pull request by sachin755**
### Proposed changes

*
*

### Related issues

*
*

### Checklist

- [x] I consider the submitted work as finished
- [x] I tested the code for its functionality
- [ ] I wrote test cases for the relevant uses case
- [ ] I added/update the relevant documentation (either on github or on notion)
- [ ] Where necessary I refactored code to improve the overall quality

### Further comments

If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Review by r-joyce — APPROVED** [review]
Looks good to me

**Comment by BigBallard** [comment]
@AMAN-SHARMA-82591 for future reference, please put reusable regex patterns in an appropriate `src/utils` file. That way, if they need to be changed for some reason, then we dont have to remember where the expression is being used. I also changed the regex for IPv6 since the original one did not account for compressed or short ipv6 patterns (perfect example of my last statement).

**Comment by BigBallard** [comment]
@johnjdl fyi above

**Review by BigBallard — APPROVED** [review]
After some minor changes I made and implementation comments, all looks good for merge.

**Comment by BigBallard** [comment]
@r-joyce ready for merge when you are ready.

**Pull request merged**
