### PR TITLE
AB#4991

### PR DESCRIPTION
**Pull request by sachin755**
### Proposed changes

*
*

### Related issues

*
*

### Checklist

- [x] I consider the submitted work as finished
- [x] I tested the code for its functionality
- [ ] I wrote test cases for the relevant uses case
- [ ] I added/update the relevant documentation (either on github or on notion)
- [ ] Where necessary I refactored code to improve the overall quality

### Further comments

If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by johnjdl** [comment]
The code looks good, though it does look like we are commenting these filters out for future use, we could probably remove these to keep from piling on some future cleanup. @r-joyce please review and merge.

**Comment by johnjdl** [comment]
@r-joyce hold on filtering, investigating functionality with Paul

**Comment by johnjdl** [comment]
@r-joyce good to review and merge.

**Review by r-joyce — APPROVED** [review]
I agree with you @johnjdl, we really should be removing these big blocks of code instead of just leaving them riddled all over the place.

@sachin755 please take note of this that we'd much rather have these types of changes as deletions instead of commenting out

**Comment by r-joyce** [comment]
There is conflicting changes with this PR and [AB#4996 #248](https://github.com/champtc/opencti/pull/248)

This PR you're commenting out the `InputLabel` components but in PR 248 you're using them, so we end up with a merge conflict.

@sachin755 please take a look at this and let us know the intent of these two PRs, thanks

**Pull request merged**
