### PR TITLE
AB#4977

### PR DESCRIPTION
**Pull request by sachin755**
### Proposed changes

*
*

### Related issues

*
*

### Checklist

- [x] I consider the submitted work as finished
- [x] I tested the code for its functionality
- [ ] I wrote test cases for the relevant uses case
- [ ] I added/update the relevant documentation (either on github or on notion)
- [ ] Where necessary I refactored code to improve the overall quality

### Further comments

If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by johnjdl** [comment]
Looks good, line 1136 in filters.js has some commented-out code we may want to remove later.
@DallasP9124 and/or @r-joyce, please take a look and merge with develop.

**Review by BigBallard — CHANGES_REQUESTED** [review]
@sachin755 the selected filters do not persist in the filter box. Whatever filter is active when that filter box is viewed, needs to be shown in the box.
[View](https://pasteboard.co/A9R2uSAaEgjN.png)
@johnjdl fyi

**Comment by BigBallard** [comment]
@CyberDaedalus00 when running this branch and attempting to filter on risk lifecycle, nothing comes back. Is there an understanding that some fields are not filterable?

**Comment by johnjdl** [comment]
@DallasP9124 @CyberDaedalus00 I can send this back to Active if needed. I think we were only concerned with the fields using the correct enums and my understanding is that the filtering is not ready on the backend.

**Comment by r-joyce** [comment]
@johnjdl @DallasP9124 @CyberDaedalus00 What is the status of this PR? Are we checking it in knowing that the backend isn't ready? Are we waiting for it to be ready to check it in?

**Comment by johnjdl** [comment]
@r-joyce good question, I think we decided to check this in and handle the backend separately.
Is that right @CyberDaedalus00?

**Review by CyberDaedalus00 — APPROVED** [review]
I'd merge this into develop as it provides an implementation.  There may still be some disconnects but we'll deal with those once merged.  There are not required backend changes.

**Review by r-joyce — APPROVED** [review]

**Pull request merged**
