### PR TITLE
bug 4263 fixed

### PR DESCRIPTION
**Pull request by AkshayMankar30**
### Proposed changes

*
*

### Related issues

*
*

### Checklist

- [x] I consider the submitted work as finished
- [x] I tested the code for its functionality
- [ ] I wrote test cases for the relevant uses case
- [ ] I added/update the relevant documentation (either on github or on notion)
- [ ] Where necessary I refactored code to improve the overall quality

### Further comments

If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Review by CyberDaedalus00 — CHANGES_REQUESTED** [review]
1. In the filter box, it still shows 'filter_labelledby' when it should show 'label'.  In addition, the field in Cyio is 'labels' where in OpenCTI they call it 'labelledby' but the fields value is very different
2. The values in the Asset Type pull down is not correct.  It should be the types of assets for ComputingDevices, which include
  * Computing Device (compute_device)
  * Appliance (appliance)
  * Workstation (workstation)
  * Network Device (network_device)
  * Load Balancer (load_balancer)
  * Printer
  * Router
  * Storage Array
  * Switch
  * VoIP Device
  * Physical Device (physical_device)

**Comment by AkshayMankar30** [comment]
Is this the right query to populate the **Asset Type** filter field, **Name** filter field, and **Labels** filter field for  **ComputingDevices**?

screenshot-studio apollographql com-2021 12 08-17_21_47

**Comment by CyberDaedalus00** [comment]
No, you must use GraphQL Interspection to do this.

`
query Introspection {
  __type(name: "AssetType") {
    name
    enumValues {
      name
      description
    }
  } 
}
`

Now I could update the GraphQL schema to make the description returned the human-label that should be displayed.

**Comment by AkshayMankar30** [comment]
@CyberDaedalus00 
1. Will this query remain the same for the **Network** Page and **Software** Page to populate the **Asset Type** filter field?
2. Will the **Asset Type** filter field values be different for both Network  & Software pages OR the same?

**Comment by CyberDaedalus00** [comment]
As a means to simplify and make predictable, I defined a new type in each of the respective GraphQL schema files for Software and ComputingDevice to allow you to (1) determine what fields are to be in the filter; and (2) what are the valid asset_type values that can be used when filtering on asset_type.

**Introspection Query to Determine Filter Fields**
To support programmatic determination of what fields can a page filter on, issue the following query for Software

`query SoftwareAssetFilterIntrospection {
  __type(name: "SoftwareAssetFilter") {
    name
    enumValues {
      name
      description
    }
  }
}
`

and the following query for ComputingDevice:
`query DeviceAssetFilterIntrospection {
  __type(name: "ComputingDeviceAssetFilter") {
    name
    enumValues {
      name
      description
    }
  }
}
`

**Introspection Query to Determine Valid Asset Type Filter Values**
To support programmatic determination of what asset_type values can be used in a filter with the asset_type field, issue the following introspection query for Software
`query SoftwareAssetTypeValues {
  __type(name: "SoftwareAssetTypes") {
    name
    description
    enumValues {
      name
      description
    }
  }
}`

and the following introspection query for Computing Device:
`query DeviceAssetTypeValues {
  __type(name: "DeviceAssetTypes") {
    name
    description
    enumValues {
      name
      description
    }
  }
}`

As for Network, you can only get the list of fields to be supported in the query as there are no support for filtering on asset_types of networks.

**Review by CyberDaedalus00 — CHANGES_REQUESTED** [review]
Please use the Introspection Queries provided as comments to the pull request to determine that contents of the filter for a given page and the appropriate set of asset_type values to be used.

**Review by CyberDaedalus00 — COMMENTED** [review]
I'm trying to figure out what the introspection.graphql file is for as I didn't see it used, and all the labels are hardcoded in the localization file.  So need to understand why this is here

**Comment by AkshayMankar30** [comment]
- It will help us to run (**asset_type**) introspection query with relay-compiler and dynamically populate the **Asset Type** filter field for Device Page. 

- And without the introspection.graphql file, the relay compiler throws the following error:

Screenshot from 2021-12-11 07-38-40

**Pull request merged**
