### PR TITLE
AB#5781 Client Server Separation

### PR DESCRIPTION
**Pull request by BigBallard**
This PR removes the single platform deployment process to a truly separated frontend client and backend server.

# Changes

## package.json

> There are no new dependencies, yay!

Most of these changes are removing script dependencies with other scripts. Mainly the `clean` script as it is not really cross-platform/CLI independent, so you would have to modify the package.json to get other scripts to run, annoying and unnecessary.

The `generate` script no longer explicitly sets the `REACT_APP_*` variables since these values are dependent on the environment so do not belong in the script, therefor need to be applied to the environment prior to running the command.

## default.json

CORS had to be configured more explicitly for the GraphQL server now since the HTTP server is not self hosting the frontend build anymore. Mainly we now need to specify acceptable origins in order for the session credentials to be sent to the client. There is a new field in the **default.json**: `app:cors:origins` that is an array of acceptable origins. This property will need to be set for local development where the client needs to communicate with the server (eg. `http://localhost:3000`). If you are just developing the server and don't need the client to be run locally than it can be ignored as the codified default is an empty array.

> ⚠️ Wildcards are **NOT** acceptable in any specified origin⚠️

## Development

The development process stands roughly the same for the client. As with the server, note the default.json changes above.

## Production and Build

The build process has some minimal changes. The `setupBuild.js` file is no longer used, so has been removed. We run the same `yarn build` to generate a production ready build of the client app. Noting the changes of the package.json, the environment variables `REACT_APP_API_URL` and `REACT_APP_GRAPHQL_HOST` need to be set prior to executing the script.

Once the build of app is complete, the build folder can now be noticed in the `opentci-platform/opencti-front` folder instead of the `.../opencti-graphql` folder.

To now serve/run the frontend application, you first need to make sure that the following environment variables are set:
* **API_URL**: The URL to the API gateway
* **SERVER_HOST**: The URL to the server
* **SSL_CRT_FILE**: The certificate file
* **SSL_KEY_FILE**: The key file
* **SSL_KEY_PASS**: The password to the key file, if needed (optional)
* **PORT**: The port to serve the app on (optional, default `8443`)

Except for the SSL_KEY_PASS and PORT variables, all variables are required for the `serve.js` script. The `serve.js` file needs to be placed in the same directory as the build folder.

Serving the application can now be done with the `node ./<path>/serve.js` command.

### CODE REVIEW

**Review by CyberDaedalus00 — APPROVED** [review]
This looks good to me.  We may need to be more explicit for folks as to what to do when they want to build just one piece.

**Review by r-joyce — APPROVED** [review]

**Comment by r-joyce** [comment]
@DallasP9124 will you please fix the merge conflicts on this? Looks to be just package related stuff. Note: with the weird issue that happened with branches, there's now a commit that says to delete some files that were created in this branch (from doing that revert commit). The easiest way to deal with it is to let it merge and delete the files, then make another commit re-adding them back to the project.

**Comment by BigBallard** [comment]
Care to link the commits? I don't notice the ones you mentioned. I'm off today but I'll try to lake a look if I get the chance.

**Comment by r-joyce** [comment]
@DallasP9124 Yeah, your on PTO, stop working

And the commit I'm talking about is [this](https://github.com/champtc/opencti/commit/6eddd317546096a68c4d8722d2ac91fd48d91cbb) one.

**Comment by r-joyce** [comment]
@DallasP9124 @CyberDaedalus00
Wanted to see if I could resolve the conflicts and noticed that it looks like there's only one and it has to do with the apollo server. In develop today it's using version 2.x, while in this split code version it's on 3.x, is everyone on the same page and alright with this PR also bumping the apollo version to 3?

**Comment by BigBallard** [comment]
That's correct. That's the other major piece to this is that we are moving to Apollo 3

**Comment by r-joyce** [comment]
@CyberDaedalus00 So if you're alright with that change I can actually fix this merge conflict now, then @DallasP9124 when you're working again, we just need to be able to merge develop into this branch, which is where that weird file deletion stuff will pop up.

**Pull request merged**
