### PR TITLE
fix: adding the notify checkbox for the new analysis modal

### PR DESCRIPTION
**Pull request by BigBallard**
Added a checkbox in the new analysis modal that will include a boolean value with the payload when submitting a new analysis request. There is also some code formatting. 

It is important to note that this **was not** a feature before. It was only defined for creating a new scan, not analysis. Therefor this is labeled as an enhancement. 

**Testing**
* Navigate to the Vulnerability Assessment page
  * Make sure you are in an org with an analysis (example)
* Click on the dropdown for an existing analysis
* Select 'New Analysis` from the menu
* Fill in the form, checking the checkbox to receive an email
* Submit

### CODE REVIEW

**Comment by BigBallard** [comment]
@johnjdl if you would mind just giving this a quick code review. @r-joyce can you do a build check. Thanks guys.

**Comment by johnjdl** [comment]
@DallasP9124 I'll take a look this afternoon.

**Review by johnjdl — APPROVED** [review]
Looks good. I was able to test locally and all seems to be working.
I received the email that my Vulnerability Scan Finished Processing (though the link from the email sent me to a dead staging link).

**Comment by BigBallard** [comment]
@johnjdl I will check with Colton on that link. Thanks

**Review by r-joyce — APPROVED** [review]
Builds clean - looks good to me, merging

**Pull request merged**
